import { motion } from "framer-motion";
import {
  Zap, Shield, Search, Repeat2, Layout, Code2, Bot, Globe, Wrench,
  CheckCircle2, ArrowRight, Database
} from "lucide-react";
import ContactForm from "@/components/ContactForm";
import { Link } from "wouter";

const fadeUp = {
  initial: { opacity: 0, y: 40 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.6, ease: "easeOut" },
};

const stagger = { animate: { transition: { staggerChildren: 0.08 } } };

const services = [
  {
    icon: <Zap size={28} className="text-yellow-400" />,
    title: "Website Speed Optimization",
    subtitle: "WordPress Performance",
    price: "$50",
    desc: "Slow websites lose visitors and rankings. I audit your site, implement caching, optimize images, minify assets, and fine-tune server configuration to dramatically cut load times.",
    includes: [
      "Full performance audit (GTmetrix / PageSpeed)",
      "Caching setup (LiteSpeed / W3TC / WP Rocket)",
      "Image compression & WebP conversion",
      "CSS/JS minification & deferring",
      "Database optimization & cleanup",
      "CDN configuration",
    ],
    color: "yellow",
  },
  {
    icon: <Shield size={28} className="text-green-400" />,
    title: "WordPress Security Optimization",
    subtitle: "Site Protection",
    price: "$50",
    desc: "Your WordPress site is constantly targeted. I harden your installation, set up firewalls, configure malware scanning, and implement backup routines to keep you protected.",
    includes: [
      "Security audit & vulnerability scan",
      "Firewall configuration (Wordfence / Sucuri)",
      "Login protection & 2FA setup",
      "SSL certificate verification",
      "Malware scanning & removal",
      "Security log monitoring setup",
    ],
    color: "green",
  },
  {
    icon: <Search size={28} className="text-blue-400" />,
    title: "WordPress On-Page SEO",
    subtitle: "Search Engine Optimization",
    price: "$50",
    desc: "Ranking on Google requires more than good content. I optimize your technical SEO foundations and on-page elements so search engines can find, crawl, and rank your site effectively.",
    includes: [
      "Technical SEO audit",
      "Meta title & description optimization",
      "Schema markup implementation",
      "Internal linking structure",
      "Image alt text & filename optimization",
      "Sitemap & robots.txt configuration",
    ],
    color: "blue",
  },
  {
    icon: <Repeat2 size={28} className="text-purple-400" />,
    title: "WordPress Website Migration",
    subtitle: "Hosting Transfers",
    price: "$50",
    desc: "Moving hosts or domains without expertise leads to downtime and data loss. I handle the full migration — files, database, DNS — with zero disruption to your visitors.",
    includes: [
      "Full site backup before migration",
      "Files & database transfer",
      "Domain & DNS configuration",
      "SSL reinstallation on new host",
      "Post-migration testing & verification",
      "Zero-downtime migration strategy",
    ],
    color: "purple",
  },
  {
    icon: <Layout size={28} className="text-pink-400" />,
    title: "Elementor Page Builder Design",
    subtitle: "Custom WordPress Design",
    price: "$50",
    desc: "Beautiful, professional pages built with Elementor Pro. From landing pages to full site redesigns — pixel-perfect, mobile-responsive, and conversion-optimized.",
    includes: [
      "Custom page design with Elementor Pro",
      "Mobile & tablet responsiveness",
      "Hover effects & animations",
      "WooCommerce product pages",
      "Header & footer design",
      "Global design system setup",
    ],
    color: "pink",
  },
  {
    icon: <Wrench size={28} className="text-orange-400" />,
    title: "WordPress Theme Cloning",
    subtitle: "Design Replication",
    price: "$50",
    desc: "Love a website's look and feel? I can reverse-engineer and replicate any design as a custom WordPress theme — keeping the aesthetic while making it fully yours.",
    includes: [
      "Design analysis & asset extraction",
      "Custom theme development",
      "Pixel-accurate layout recreation",
      "Full Elementor integration",
      "Responsive across all devices",
      "Clean, maintainable code output",
    ],
    color: "orange",
  },
  {
    icon: <Code2 size={28} className="text-cyan-400" />,
    title: "AI HTML to WordPress",
    subtitle: "AI Code Conversion",
    price: "$50",
    desc: "Have a beautiful HTML site generated by an AI tool? I convert it into a fully functional WordPress site with proper templates, plugins, and CMS integration.",
    includes: [
      "HTML/CSS analysis & cleanup",
      "WordPress theme creation from HTML",
      "Gutenberg or Elementor integration",
      "Plugin setup & configuration",
      "Content migration into WordPress",
      "Full mobile responsiveness check",
    ],
    color: "cyan",
  },
  {
    icon: <Bot size={28} className="text-indigo-400" />,
    title: "AI Code Writing Services",
    subtitle: "Claude | Gemini | Replit | Lovable",
    price: "$50",
    desc: "I write, prompt, and refine code using the leading AI platforms. Get website code, features, and complete projects powered by AI — delivered clean and production-ready.",
    includes: [
      "Claude AI code generation & refinement",
      "Google AI Studio project builds",
      "Replit AI web app development",
      "Lovable AI design implementation",
      "Custom prompting & iteration",
      "Code review & optimization",
    ],
    color: "indigo",
  },
  {
    icon: <Globe size={28} className="text-teal-400" />,
    title: "WordPress Website Builds",
    subtitle: "E-Commerce | LMS | Business | Portfolio | Booking",
    price: "$150",
    desc: "Full website builds from the ground up. Whatever type of site your business needs, I design, build, and launch it — ready for real visitors on day one.",
    includes: [
      "E-Commerce (WooCommerce) stores",
      "LMS websites (LearnDash / Tutor LMS)",
      "Business & corporate websites",
      "Portfolio & personal brand sites",
      "Service booking websites",
      "Post-launch support included",
    ],
    color: "teal",
  },
  {
    icon: <Database size={28} className="text-rose-400" />,
    title: "Website Backup Optimization",
    subtitle: "Data Protection",
    price: "$50",
    desc: "Automated, reliable backups that run without you thinking about them. Stored securely off-site so you can restore your site in minutes if anything goes wrong.",
    includes: [
      "Automated daily/weekly backups",
      "Cloud storage integration (S3/Dropbox/Google Drive)",
      "Database & file backup configuration",
      "Backup testing & restoration drills",
      "Retention policy setup",
      "Emergency restore support",
    ],
    color: "rose",
  },
];

const colorMap: Record<string, string> = {
  yellow: "text-yellow-400 bg-yellow-400/10",
  green: "text-green-400 bg-green-400/10",
  blue: "text-blue-400 bg-blue-400/10",
  purple: "text-purple-400 bg-purple-400/10",
  pink: "text-pink-400 bg-pink-400/10",
  orange: "text-orange-400 bg-orange-400/10",
  cyan: "text-cyan-400 bg-cyan-400/10",
  indigo: "text-indigo-400 bg-indigo-400/10",
  teal: "text-teal-400 bg-teal-400/10",
  rose: "text-rose-400 bg-rose-400/10",
};

export default function Services() {
  return (
    <div className="min-h-screen pt-16">
      {/* Header */}
      <section className="relative py-24 px-4 sm:px-6 lg:px-8 overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-0 right-1/4 w-96 h-96 bg-blue-600/15 rounded-full blur-3xl" />
          <div className="absolute bottom-0 left-1/4 w-96 h-96 bg-purple-600/15 rounded-full blur-3xl" />
        </div>
        <div className="max-w-4xl mx-auto text-center">
          <motion.div {...fadeUp}>
            <span className="text-blue-400 text-sm font-semibold uppercase tracking-widest mb-4 block">What I Offer</span>
            <h1 className="text-5xl sm:text-6xl font-bold text-white mb-6 leading-tight">
              Professional <span className="gradient-text">Web Services</span>
            </h1>
            <p className="text-gray-400 text-xl leading-relaxed max-w-2xl mx-auto">
              Every service is designed around real outcomes — faster sites, higher rankings, stronger security, and more business. Browse what Ahmed can do for you.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Service Cards */}
      <section className="py-10 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto">
          <motion.div
            variants={stagger}
            initial="initial"
            animate="animate"
            className="grid grid-cols-1 lg:grid-cols-2 gap-8"
          >
            {services.map((service, i) => (
              <motion.div
                key={service.title}
                variants={fadeUp}
                className="glass-card p-8 rounded-2xl group"
                data-testid={`card-service-${i}`}
              >
                <div className="flex items-start justify-between gap-4 mb-5">
                  <div className="flex items-start gap-4">
                    <div className={`w-14 h-14 rounded-2xl flex items-center justify-center shrink-0 ${colorMap[service.color]}`}>
                      {service.icon}
                    </div>
                    <div>
                      <span className={`text-xs font-semibold uppercase tracking-wider ${colorMap[service.color].split(" ")[0]}`}>
                        {service.subtitle}
                      </span>
                      <h3 className="text-white font-bold text-xl mt-1">{service.title}</h3>
                    </div>
                  </div>
                  <div className="shrink-0 text-right">
                    <div className="gradient-text text-2xl font-bold leading-none">{service.price}</div>
                    <div className="text-gray-500 text-xs mt-1">per project</div>
                  </div>
                </div>
                <p className="text-gray-400 text-sm leading-relaxed mb-6">{service.desc}</p>
                <div>
                  <h4 className="text-gray-300 text-xs font-semibold uppercase tracking-wider mb-3">What's Included</h4>
                  <ul className="space-y-2">
                    {service.includes.map((item) => (
                      <li key={item} className="flex items-center gap-3 text-gray-400 text-sm">
                        <CheckCircle2 size={14} className={colorMap[service.color].split(" ")[0] + " shrink-0"} />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className="flex items-center justify-between mt-6 pt-5 border-t border-white/5">
                  <span className="text-gray-500 text-sm">Starting from <span className="text-white font-semibold">{service.price}</span></span>
                  <Link href="/service-booking" data-testid={`link-service-book-${i}`}>
                    <button className="gradient-btn text-white text-sm font-semibold px-4 py-2 rounded-xl flex items-center gap-2">
                      Book Now <ArrowRight size={14} />
                    </button>
                  </Link>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* Contact Form */}
      <section className="py-24 px-4 sm:px-6 lg:px-8 bg-white/[0.02] mt-16">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
            className="text-center mb-12"
          >
            <span className="text-blue-400 text-sm font-semibold uppercase tracking-widest mb-4 block">Ready?</span>
            <h2 className="text-4xl font-bold text-white mb-4">Book a Service or <span className="gradient-text">Ask a Question</span></h2>
            <p className="text-gray-400 max-w-xl mx-auto">
              Select the service you are interested in and Ahmed will be in touch with a tailored plan and pricing.
            </p>
          </motion.div>
          <motion.div
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            viewport={{ once: true }}
          >
            <ContactForm
              heading="Enquire About a Service"
              subheading="Tell Ahmed what you need and he will respond within 24 hours with next steps."
            />
          </motion.div>
        </div>
      </section>
    </div>
  );
}
